repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint-full

  - repo: local
    hooks:
      - id: generate
        name: generate
        entry: make generate
        verbose: true
        language: system
        types: [go, css]
