name: oar

services:
  oar:
    image: ghcr.io/ch00k/oar:0.0.5
    environment:
      OAR_HTTP_HOST: 0.0.0.0
      OAR_HTTP_PORT: 8080
      OAR_LOG_LEVEL: info
      OAR_DATA_DIR: /data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
