name: oar

services:
  oar:
    image: oar:latest
    environment:
      OAR_HTTP_HOST: 0.0.0.0
      OAR_HTTP_PORT: 8080
      OAR_LOG_LEVEL: info
      OAR_DATA_DIR: /data
      USER_ID: "${UID:-1000}"
      GROUP_ID: "${GID:-1000}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 127.0.0.1:8080:8080
