name: oar

services:
  oar:
    image: ghcr.io/ch00k/oar:0.0.14
    user: ${OAR_UID:-1000}:${OAR_GID:-1000}
    environment:
      OAR_HTTP_HOST: 0.0.0.0
      OAR_HTTP_PORT: 8080
      OAR_LOG_LEVEL: info
      OAR_DATA_DIR: /data
      OAR_CONTAINERIZED: true
      OAR_ENCRYPTION_KEY: ${OAR_ENCRYPTION_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "8080"]
      interval: 2s
      timeout: 1s
      retries: 10
    restart: unless-stopped
