name: oar

services:
  web:
    image: ghcr.io/oar-cd/oar-web:0.0.24
    user: ${OAR_UID:-1000}:${OAR_GID:-1000}
    environment:
      OAR_HTTP_HOST: 0.0.0.0
      OAR_HTTP_PORT: 8080
      OAR_LOG_LEVEL: info
      OAR_DATA_DIR: /data
      OAR_HOST_DATA_DIR: ${PWD}/data
      OAR_CONTAINERIZED: true
      OAR_ENCRYPTION_KEY: ${OAR_ENCRYPTION_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 127.0.0.1:8080:8080
    restart: unless-stopped

  watcher:
    image: ghcr.io/oar-cd/oar-watcher:0.0.24
    user: ${OAR_UID:-1000}:${OAR_GID:-1000}
    environment:
      OAR_LOG_LEVEL: info
      OAR_DATA_DIR: /data
      OAR_HOST_DATA_DIR: ${PWD}/data
      OAR_CONTAINERIZED: true
      OAR_POLL_INTERVAL: ${OAR_POLL_INTERVAL:-5m}
      OAR_ENCRYPTION_KEY: ${OAR_ENCRYPTION_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
