name: ci
on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - uses: golangci/golangci-lint-action@v8.0.0
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - run: make test_ci
