name: Build and publish release artifacts

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_WEB: ${{ github.repository }}-web
  IMAGE_NAME_WATCHER: ${{ github.repository }}-watcher

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Wait for CI to pass
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          check-name: Lint
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5

      - name: Wait for tests to pass
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          check-name: Test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get image tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract web metadata
        id: meta-web
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest

      - name: Extract watcher metadata
        id: meta-watcher
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WATCHER }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push web Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
          file: web/Dockerfile
          build-args: |
            VERSION=${{ steps.version.outputs.version }}

      - name: Build and push watcher Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta-watcher.outputs.tags }}
          labels: ${{ steps.meta-watcher.outputs.labels }}
          file: watcher/Dockerfile
          build-args: |
            VERSION=${{ steps.version.outputs.version }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libc6-dev

      - name: Build CLI binary
        run: CGO_ENABLED=1 go build -ldflags="-s -w -X github.com/oar-cd/oar/cmd/version.CLIVersion=${{ steps.version.outputs.version }}" -o oar-linux-amd64 ./cmd

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            compose.yaml
            oar-linux-amd64
          generate_release_notes: true
